### ISSUE TITLE
Release 2025 task list

### ISSUE THREAD

**Issue by mchamberland** [clrp-code/egs_brachy#68]
This issue is used to track progress towards a 2025 release of egs_brachy.

- [ ] Add DRC and air-kerma per history factor table to the manual.
- [ ] Explicitly point out differences in results normalization between egs_brachy and other EGSnrc applications.
- [ ] Add volume correction coverage threshold example.
- [ ] Add eye plaque geometries to manual.
- [ ] Fix paths in eye plaque sample input files.
- [ ] Add eye egsphant to phantom library.
- [ ] Clean up eye plaque library.
- [ ] Review and add wrapped source geometries as needed.
- [ ] Add CLRP database papers to the repository.
- [ ] Add best practices section to the documentation.
- [ ] Add egs_brachy as an EGSnrc git submodule.
- [ ] Add references to eb_gui.
